/*
This file was generated by the ToffeeCompiler utility.
*/
using Toffee.Core;
using Toffee.Core.Objects;
using Toffee.Core.Definitions;
using Toffee.Core.Definitions.Attributes;
using System.CodeDom.Compiler;

namespace Toffee.Core.Packets.Internal
{
	[GeneratedCode("ToffeeCompiler", "csharp")]	
	[ToffeeStructure("StdToffee")]
	public partial class InternalHelloResponse : IToffeeStructure
	{
		[ToffeeStructureProperty(1)]
		public bool Sucess { get; set; }
		
		[ToffeeStructureProperty(2)]
		public byte ErrorCode { get; set; }
		
		[ToffeeStructureProperty(3)]
		public string Message { get; set; }
		
		[ToffeeStructureProperty(4)]
		public uint Channel { get; set; }
		
		public void WriteTo(ToffeePacket packet)
		{
			packet.Write(Sucess);
			packet.Write(ErrorCode);
			packet.Write(Message);
			packet.Write(Channel);
		}
		
		public void ReadFrom(ToffeePacketIterator iterator)
		{
			Sucess = iterator.ReadBoolean();
			ErrorCode = iterator.ReadUInt8();
			Message = iterator.ReadString();
			Channel = iterator.ReadUInt32();
		}
	}
}
