/*
This file was generated by the ToffeeCompiler utility.
*/
using Toffee.Core;
using Toffee.Protocol.Objects;
using Toffee.Protocol.Definitions;
using Toffee.Protocol.Definitions.Attributes;
using System.CodeDom.Compiler;

namespace Toffee.Protocol.Packets
{
	[GeneratedCode("ToffeeCompiler", "csharp")]	
	[ToffeeStructure("StdToffee")]
	public partial class FieldUpdate : IToffeeStructure
	{
		[ToffeeStructureProperty(1)]
		public uint FieldId { get; set; }
		
		[ToffeeStructureProperty(2)]
		public byte[] Parameters { get; set; }
		
		public void WriteTo(ToffeePacket packet)
		{
			packet.Write(FieldId);
			packet.Write(Parameters);
		}
		
		public void ReadFrom(ToffeePacketIterator iterator)
		{
			FieldId = iterator.ReadUInt32();
			Parameters = (byte[])iterator.ReadArray();
		}
	}
}
