/*
This file was generated by the ToffeeCompiler utility.
*/
using Toffee.Core;
using Toffee.Protocol.Objects;
using Toffee.Protocol.Definitions;
using Toffee.Protocol.Definitions.Attributes;
using System.CodeDom.Compiler;
using Toffee.Protocol.Packets.Objects;

namespace Toffee.Protocol.Packets.Services
{
	[GeneratedCode("ToffeeCompiler", "csharp")]	
	[ToffeeStructure("StdToffee")]
	public partial class ServiceOpen : IToffeeStructure
	{
		[ToffeeStructureProperty(1)]
		public uint DistributedId { get; set; }
		
		[ToffeeStructureProperty(2)]
		public uint ServiceType { get; set; }
		
		[ToffeeStructureProperty(3)]
		public FieldUpdate[] CurrentState { get; set; }
		
		public void WriteTo(ToffeePacket packet)
		{
			packet.Write(DistributedId);
			packet.Write(ServiceType);
			packet.Write(CurrentState);
		}
		
		public void ReadFrom(ToffeePacketIterator iterator)
		{
			DistributedId = iterator.ReadUInt32();
			ServiceType = iterator.ReadUInt32();
			CurrentState = (FieldUpdate[])iterator.ReadArray();
		}
	}
}
