/*
This file was generated by the ToffeeCompiler utility.
*/
using Toffee.Core;
using Toffee.Core.Objects;
using Toffee.Core.Definitions;
using Toffee.Core.Definitions.Attributes;
using System.CodeDom.Compiler;

namespace Toffee.Core.Packets.Client
{
	[GeneratedCode("ToffeeCompiler", "csharp")]	
	[ToffeeStructure("StdToffee")]
	public partial class ClientPacketHeader : IToffeeStructure
	{
		[ToffeeStructureProperty(1)]
		public ushort OpCode { get; set; }
		
		[ToffeeStructureProperty(2)]
		public bool Compressed { get; set; }
		
		[ToffeeStructureProperty(3)]
		public long Timestamp { get; set; }
		
		[ToffeeStructureProperty(4)]
		public ushort Length { get; set; }
		
		public void WriteTo(ToffeePacket packet)
		{
			packet.Write(OpCode);
			packet.Write(Compressed);
			packet.Write(Timestamp);
			packet.Write(Length);
		}
		
		public void ReadFrom(ToffeePacketIterator iterator)
		{
			OpCode = iterator.ReadUInt16();
			Compressed = iterator.ReadBoolean();
			Timestamp = iterator.ReadInt64();
			Length = iterator.ReadUInt16();
		}
	}
}
